/**
 * Every icon in Aloft is routed through this module, so the icon set is a
 * single decision rather than 40 scattered imports. Phosphor is used at
 * "bold" weight for navigation and "regular" elsewhere; nothing in the UI
 * is ever an emoji.
 */
export {
  Broadcast as IconScope,
  Garage as IconHangar,
  UsersThree as IconSpotters,
  Sliders as IconSystem,
  Crosshair as IconHunt,
  CrosshairSimple as IconReticle,
  AirplaneTilt as IconAircraft,
  AirplaneInFlight as IconInFlight,
  AirplaneTakeoff as IconDeparture,
  ArrowUp as IconUp,
  ArrowRight as IconArrow,
  CaretLeft as IconBack,
  CaretLeft as IconCaretLeft,
  CaretRight as IconCaretRight,
  X as IconClose,
  Plus as IconAdd,
  Check as IconCheck,
  Warning as IconWarning,
  Info as IconInfo,
  Bell as IconBell,
  ShareNetwork as IconShare,
  ArrowsClockwise as IconRefresh,
  Copy as IconCopy,
  SpeakerHigh as IconSound,
  SpeakerSlash as IconMuted,
  MapPin as IconPin,
  Path as IconRoute,
  Gauge as IconSpeed,
  Compass as IconBearing,
  Ruler as IconRange,
  Trophy as IconTrophy,
  Medal as IconMedal,
  Fire as IconStreak,
  Star as IconStar,
  Moon as IconNight,
  Mountains as IconAltitude,
  Lightning as IconFast,
  Timer as IconTimer,
  Barcode as IconRegistration,
  CircleNotch as IconSpinner,
  DownloadSimple as IconInstall,
  Person as IconPerson,
  Trash as IconRemove,
  CellTower as IconTower,
  GlobeHemisphereWest as IconWorld,
} from "@phosphor-icons/react";
